### ISSUE TITLE
Use datasets to mark cartodbfied tables

### ISSUE THREAD

**Issue by jsanz** [CartoDB/labs-db-metrics#6]
Instead of checking columns and indexes 

https://github.com/CartoDB/labs-db-metrics/blob/58d8c5d3e8fa8d5c0bd3fa29474ebbdae525427e/carto_report/report.py#L215

...the script already has the needed information to mark which tables are cartodbfied. Alternatively, this query can also be used to get them in a single query

```sql
select * from CDB_TableMetadata_Text where tabname like 'schema_name%'
```

Where `schema_name` is the user name on accounts with an organization and `public` on accounts without an org.

**Comment by ramiroaznar** [comment]
Fixed on https://github.com/CartoDB/labs-db-metrics/pull/5
